### ISSUE TITLE
starting golem app on os x 10.11.6

### ISSUE THREAD

**Issue by zdavatz** [golemfactory/homebrew-golem#1]
Hi, 

starting the golemapp on os x 10.11.6 I get:
```
golemapp --verbose
Error loading Python lib '/var/folders/xb/n8k9dz4d2vnb3k9q5m7bv5_80000gn/T/_MEIYX4QS5/Python': dlopen(/var/folders/xb/n8k9dz4d2vnb3k9q5m7bv5_80000gn/T/_MEIYX4QS5/Python, 10): Symbol not found: _getentropy
  Referenced from: /var/folders/xb/n8k9dz4d2vnb3k9q5m7bv5_80000gn/T/_MEIYX4QS5/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/xb/n8k9dz4d2vnb3k9q5m7bv5_80000gn/T/_MEIYX4QS5/Python
```
any hints how to proceed?

**Comment by jkcailteux** [comment]
Since python comes pre-installed on Mac, i wonder if they have an intended version that must be used. Did you change your default version of python?

**Comment by perceptbe** [comment]
Same issue:

`Percept [23:33:30] /Users/Percept
➥  golemapp
Error loading Python lib '/var/folders/3c/n7wbsct54yxbpl07_3lx8y_c0000gn/T/_MEI8mLu6z/Python': dlopen(/var/folders/3c/n7wbsct54yxbpl07_3lx8y_c0000gn/T/_MEI8mLu6z/Python, 10): Symbol not found: _getentropy
  Referenced from: /var/folders/3c/n7wbsct54yxbpl07_3lx8y_c0000gn/T/_MEI8mLu6z/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/3c/n7wbsct54yxbpl07_3lx8y_c0000gn/T/_MEI8mLu6z/Python`

**Comment by zdavatz** [comment]
No I did not.

**Comment by gborowik** [comment]
Golem v0.4.0 for macOS is now available for previous versions of Apple’s systems. Please check how to reinstall https://github.com/golemfactory/homebrew-golem

**Comment by zdavatz** [comment]
Thank you!
