### ISSUE TITLE
Installation: Error: Failed to download resource "hyperg"

### ISSUE THREAD

**Issue by dskvr** [golemfactory/homebrew-golem#12]
Ethereum installed correctly, checked by running `geth` 

Followed directions for golem install, and got 

```
Error: Failed to download resource "hyperg"
Download failed: https://github.com/mfranciszkiewicz/golem-hyperdrive/releases/download/v0.2.0/hyperg_0.2.0_darwin-x64.tar.gz
````

How do I proceed?

**Comment by jet86** [comment]
Are there any indicators of why it failed?
Have you done `brew update && brew upgrade` before trying to install golemapp?
Do you get any warnings or errors when running `brew doctor` ?

**Comment by maaktweluit** [comment]
@dskvr Did not hear back from you, hope the tip @jet86 gave solved the issue for you.

If not please update to the latest version and re-open when you still have the same error.
