### ISSUE TITLE
Failure in brew cask install golem

### ISSUE THREAD

**Issue by karolistamutis** [golemfactory/homebrew-golem#16]
Hi guys,

I've got dockermachine-driver-xhyve installed already and ran the chown separately but golem bottle still wants to run it and fails - I don't get prompt for password however. Anyone has this problem? I'm on macOS Sierra 10.12.6

```
sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

Error: Failed executing: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem/golem.rb:26:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1093:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1905:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1884:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:114:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:188:in `<main>'
```

**Comment by jlass192** [comment]
Having the exact same problem on Sierra 10.12.6

**Comment by Tufalentes** [comment]
Same problem here.
Tried to uninstall and reinstall and had the same problem again.

Installation was previously aborted here:
curl: (18) transfer closed with 63619339 bytes remaining to read
Error: Failed to download resource "golem"
Download failed: https://github.com/golemfactory/golem/releases/download/0.7.1/golem-macos-0.7.1.tar.gz

Using Sierra 10.12.5

**Comment by gborowik** [comment]
This problem is very specific to xhyve driver and running chown with sudo is a must. Please refer to the Install section here: https://github.com/zchee/docker-machine-driver-xhyve
Considering that you prefer to have dedicated bottle please downlowd golem.rb and withdraw those two lines.

**Comment by karolistamutis** [comment]
Thanks, installed by commenting below lines in /usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem/golem.rb

```
    #system 'echo docker-machine-driver-xhyve need root owner and uid'
    #system "sudo chown root:wheel #{HOMEBREW_PREFIX}/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve"
    #system "sudo chmod u+s #{HOMEBREW_PREFIX}/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve"
```

**Comment by jlass192** [comment]
Hello. n00b question here (I'm not a programmer but am interested in Golem). I am still unsure how to proceed. I've installed docker-machine-driver-xhyve as described in the zchee thread yet still getting the same error. Do I need to download golem.rb and run in exe format? What's the correct input for HOMEBREW_PREFIX? Thanks for your help! Look forward to helping this interesting project move forward.

**Comment by jpita** [comment]
@jlass192 still need help?

**Comment by jlass192** [comment]
Hi @jpita . Yes, I am still unable to install due to what I've explained above - any help you can offer would be very much appreciated!

**Comment by jpita** [comment]
@jlass192 ok, let's see if I can give you a step by step:

1. open the terminal (`cmd` + `space` keys, write `terminal` and press `enter` )
2. write `nano /usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem/golem.rb` and press `enter`
3. use the arrow keys to go to the lines mentioned here https://github.com/golemfactory/homebrew-golem/issues/16#issuecomment-319932746
4. on each line, add a `#` in the beginning of the line
5. press `ctrl` + `x` keys
6. press `y` key
7. press `enter` key

try to install again by running `brew cask install golem` and let me know if it helped

**Comment by jlass192** [comment]
@jpita you're the best. that worked perfectly - thank you!
