### ISSUE TITLE
sudo commands in installation throw error

### ISSUE THREAD

**Issue by aeftimia** [golemfactory/homebrew-golem#17]
Homebrew seemed to have trouble installing golem when setting xhyve permissions with sudo. Homebrew in general doesn't seem to like using sudo, and ome guides I've found online for xhyve and other software that use it provide instructions to set permissions for xhyve manually. I've reset my homebrew installation and permissions for my homebrew directory.

Anyone else had problems with this? Maybe it's worth removing the sudos from the installer and suggested in the README for the user to do separately.

brew cask install golem
==> Satisfying dependencies
==> Installing Formula dependencies: golem
==> Installing golemfactory/golem/golem
==> Downloading https://github.com/golemfactory/golem/releases/download/0.7.1/golem-macos-0.7.1.tar.gz
Already downloaded: /Users/aeftimia/Library/Caches/Homebrew/golem-0.7.1.tar.gz
==> echo docker-machine-driver-xhyve need root owner and uid
==> sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Last 15 lines from /Users/aeftimia/Library/Logs/Homebrew/golem/02.docker-machine-driver-xhyve:
2017-08-08 21:03:10 -0400

sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

Error: Failed executing: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem/golem.rb:26:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1093:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1905:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1884:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:114:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:188:in `<main>'

**Comment by gborowik** [comment]
Please check this thread: https://github.com/golemfactory/homebrew-golem/issues/16
