### ISSUE TITLE
Can't get app installed related to docker-machine

### ISSUE THREAD

**Issue by perceptbe** [golemfactory/homebrew-golem#4]
Percept [21:34:44] /Users/Percept
➥  brew install golem
==> Installing golem from golemfactory/golem
Error: You must `brew link docker docker-machine` before golemfactory/golem/golem can be installed
---
Percept [21:36:00] /Users/Percept
➥  brew link docker docker-machine
Linking /usr/local/Cellar/docker/17.03.1...
Error: Could not symlink bin/docker
Target /usr/local/bin/docker
already exists. You may want to remove it:
  rm '/usr/local/bin/docker'

To force the link and overwrite all conflicting files:
  brew link --overwrite docker

To list all files that would be deleted:
  brew link --overwrite --dry-run docker
---
Percept [21:39:35] /Users/Percept
➥  brew link --overwrite docker
Linking /usr/local/Cellar/docker/17.03.1... 4 symlinks created
---
Percept [21:41:53] /Users/Percept
➥  brew install golem
==> Installing golem from golemfactory/golem
Error: You must `brew link docker-machine` before golemfactory/golem/golem can be installed

----
wth is up with this github editor

**Comment by gborowik** [comment]
Probably you have an older docker already installed and a new version is available. Please try `brew update` and `brew upgrade`.
After upgrade try install golem again.

**Comment by perceptbe** [comment]
I had to remove an old Docker version from /usr/local/bin/docker-machine

brew unlink docker-machine
brew link docker-machine
and then the golem install worked
